config/routes.rb
Rails.application.routes.draw do
  resources :turns
  devise_for :users
  resources :users, path: '/users_admin'
  

  resources :localities
  resources :sucursals
    
  resources :horarios

  get 'index/home'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "index#home"
end

app/models/locality.rb
class Locality < ApplicationRecord
    has_many :sucursal #optional: true

    validates :name, uniqueness: { case_sensitive: false }
    validates :province, presence: true

    enum :province, [ :buenos_aires, :catamarca, :chaco, :chubut, :cordoba, :corrientes, :entre_rios, :formosa, :jujuy, :la_pampa, :la_rioja, :mendoza, 
    :misiones, :neuquen, :rio_negro, :salta, :san_juan, :san_luis, :santa_cruz, :santa_fe, :santiago_del_estero, :tierra_del_fuego, :tucuman]
end

app/controllers/localities_controller.rb
class LocalitiesController < ApplicationController
  before_action :set_locality, only: %i[ show edit update destroy ]

  # GET /localities or /localities.json
  def index
    @localities = Locality.all
  end

  # GET /localities/1 or /localities/1.json
  def show
  end

  # GET /localities/new
  def new
    @locality = Locality.new
  end

  # GET /localities/1/edit
  def edit
  end

  # POST /localities or /localities.json
  def create
    @locality = Locality.new(locality_params)
    @locality.name = @locality.name.upcase

    respond_to do |format|
      if @locality.save
        format.html { redirect_to locality_url(@locality), notice: "Locality was successfully created." }
        format.json { render :show, status: :created, location: @locality }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @locality.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /localities/1 or /localities/1.json
  def update
    respond_to do |format|
      if @locality.update(locality_params)
        format.html { redirect_to locality_url(@locality), notice: "Locality was successfully updated." }
        format.json { render :show, status: :ok, location: @locality }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @locality.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /localities/1 or /localities/1.json
  def destroy
    if Sucursal.localities_sucursal(@locality.id).empty?
      @locality.destroy

      respond_to do |format|
        format.html { redirect_to localities_url, notice: "Locality was successfully destroyed." }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to localities_url, notice: "La localidad no puede ser eliminada" }
        format.json { render json: @locality.errors, status: :unprocessable_entity  }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_locality
      @locality = Locality.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def locality_params
      params.require(:locality).permit(:province, :name, :sucursal_id)
    end
end

app/helpers/localities_helper.rb
module LocalitiesHelper

    def get_provinces
        {
            "Buenos Aires" => :buenos_aires,
            "Catamarca" => :catamarca,
            "Chaco" => :chaco,
            "Chubut" => :chubut,
            "Córdoba" => :cordoba,
            "Corrientes" => :corrientes,
            "Entre Ríos" => :entre_ríos,
            "Formosa" => :formosa,
            "Jujuy" => :jujuy,
            "La Pampa" => :la_pampa,
            "La Rioja" => :la_rioja,
            "Mendoza" => :mendoza,
            "Misiones" => :misiones,
            "Neuquén" => :neuquen,
            "Río Negro" => :rio_negro,
            "Salta" => :salta,
            "San Juan" => :san_juan,
            "San Luis" => :san_luis,
            "Santa Cruz" => :santa_cruz,
            "Santa Fe" => :santa_fe,
            "Santiago del Estero" => :santiago_del_estero,
            "Tierra del Fuego" => :tierra_del_fuego,
            "Tucumán" => :tucuman
        }
    end

end

app/views/localities/_form.html.erb
<div class="row">
  <div class="col-log-12">
    <div class="card p-5"> 
      <%= form_with(model: locality) do |form| %>
        <% if locality.errors.any? %>
          <div style="color: red">
            <h2><%= pluralize(locality.errors.count, "error") %> prohibited this locality from being saved:</h2>

            <ul>
              <% locality.errors.each do |error| %>
                <li><%= error.full_message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div>
          <%= form.label :province, style: "display: block" %>
          <%= form.select :province, options_for_select(get_provinces, locality.province) %>
        </div>

        <div>
          <%= form.label :name, style: "display: block" %>
          <%= form.text_field :name %>
        </div>

        <div>
          <%= form.submit "Guardar"%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/localities/_locality.html.erb
<div id="<%= dom_id locality %>">
  <p>
    <strong>Province:</strong>
    <%= locality.province %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= locality.name %>
  </p>

  <p>
    <strong>Sucursal:</strong>
    <%= locality.sucursal_id %>
  </p>

</div>

app/views/localities/edit.html.erb
<h1>Editar localidad</h1>

<%= render "form", locality: @locality %>

<br>

<div>
  <%= link_to "Ver localidad", @locality %> |
  <%= link_to "Volver al listado", localities_path %>
</div>

app/views/localities/index.html.erb
<center><h1> Lista de localidades </h1></center>
<br><br>
<a href="<%= new_locality_path %>" class="btn btn-primary btn-icon-split">
  <span class="icon text-white-50">
    <i class="fas fa-flag"></i>
    </span>
    <span class="text"> Crear localidad</span>
</a>

<br><br>
<table class="table">
  <thead>
    <th>Nombre</th>
    <th>Provincia</th>
    <th></th>
    
  </thead>
  <tbody>
  <% @localities.each do |locality|  %>
    <tr>
       <td> <%= locality.name %> </td>
       <td> <%= locality.province %> </td>
       

       <td> <%= link_to "Detalles", locality_path(locality), class: "btn btn-primary" %> </td>
     </tr>
  <% end %>
  </tbody>
</table>

app/views/localities/new.html.erb
<h1>Nueva localidad</h1>

<%= render "form", locality: @locality %>

<br>

<div>
  <%= link_to "Volver al listado", localities_path %>
</div>

app/views/localities/show.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1>Detalles de la localidad</h1>    
    
    <div class="card">
      <table class="table">
        <tr>
          <td><b>Nombre: </b></td>
          <td><%= @locality.name %></td>
        </tr>
        <tr>
          <td><b>Provincia: </b></td>
          <td><%= @locality.province %></td>
        </tr>
        <tr> 
        </tr>
      
      </table>
    </div>
    

    
    </div>
    
    <%= link_to "Editar localidad", edit_locality_path(@locality), class: 'btn btn-warning' %>
    <%= button_to "Eliminar localidad", @locality, form: { data: { turbo_confirm: "Estas seguro?" } },method: :delete, class: 'btn btn-danger' %>
    <%= link_to "Volver al listado", localities_path, class: 'btn btn-outline-primary' %>
</div>