config/routes.rb
Rails.application.routes.draw do
  resources :turns
  devise_for :users
  resources :users, path: '/users_admin'
  

  resources :localities
  resources :sucursals
    
  resources :horarios

  get 'index/home'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "index#home"
end

app/models/turn.rb
class Turn < ApplicationRecord
  belongs_to :sucursal
  belongs_to :user
  belongs_to :employee, class_name: "User", optional:true

  validates :sucursal_id, presence: true 
  validates :user_id, presence: true 
  validates :date, presence: true 
  validates :motive, presence: true

  enum :status, [:pendiente, :cancelado, :atendido]

  def self.turns_sucursal(sucursal)
    Turn.all.where(sucursal_id: sucursal, status: 'pendiente')     
  end

  def self.validar_fecha_hora(date, id_suc)
    date = date.to_datetime
    if date.to_date > DateTime.now.to_date
      p horarios = Horario.where(sucursal_id: id_suc) 
      horarios.each do |hora|
        if hora.dia = date.strftime("%A").downcase
          return date.strftime("%H:%M").between?(hora.desde.strftime("%H:%M"),hora.hasta.strftime("%H:%M"))
        else 
          return false
        end
      end
    else 
      return false
    end
  end

  def self.turns_personal(personal)
    Turn.where('employee_id:? OR user_id:?', personal, personal)
  end

  def self.eliminar(turnos)
    if !turnos.empty?
      turnos.each do |turn|
        turn.destroy
      end
    end
  end

end

app/controllers/turns_controller.rb
class TurnsController < ApplicationController
  before_action :set_turn, only: %i[ show edit update destroy ]

  # GET /turns or /turns.json
  def index    
    @turns = current_user.turns.order(:date => :asc)
  end

  # GET /turns/1 or /turns/1.json
  def show
  end

  # GET /turns/new
  def new
    @turn = Turn.new
  end

  # GET /turns/1/edit
  def edit
  end

  # POST /turns or /turns.json
  def create
    @turn = Turn.new(turn_params)
    @turn.user_id = current_user.id
  
    respond_to do |format|
      if Sucursal.dia_horario(@turn)
        if @turn.save
          format.html { redirect_to turn_url(@turn), notice: "Turn was successfully created." }
          format.json { render :show, status: :created, location: @turn }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @turn.errors, status: :unprocessable_entity }
        end
      
      else       
        @turn.errors.add(:date, :invalid)
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @turn.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /turns/1 or /turns/1.json
  def update
    @user = current_user
    if @user.rol == 'personal_bancario'
      @turn.employee_id = current_user.id 
      @turn.status = 'atendido'
      update_turn(@turn)
    else @user.rol == 'cliente'
        if Turn.validar_fecha_hora(turn_params[:date], turn_params[:sucursal_id])
          update_turn(@turn)
        else 
          @turn.errors.add(:date, :invalid)
          respond_to do |format|
            format.html { render :edit, status: :unprocessable_entity }
            format.json { render json: @turn.errors, status: :unprocessable_entity }
          end
        end
    end
  end

  # DELETE /turns/1 or /turns/1.json
  def destroy
    @turn.destroy

    respond_to do |format|
      format.html { redirect_to turns_url, notice: "Turn was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_turn
      @turn = Turn.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def turn_params
      params.require(:turn).permit(:date, :motive, :status, :result, :sucursal_id, :user_id)
    end

    def update_turn(turn)
      respond_to do |format|      
        if turn.update(turn_params)
          format.html { redirect_to turn_url(turn), notice: "Turn was successfully updated." }
          format.json { render :show, status: :ok, location: turn }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: turn.errors, status: :unprocessable_entity }
        end
      end
    end
end

app/helpers/turns_helper.rb
module TurnsHelper
end

app/views/turns/_form.html.erb
<div class="row">
  <div class="col-log-12">
    <div class="card p-5">

      <%= form_with(model: turn) do |form| %>
        <% if turn.errors.any? %>
          <div style="color: red">
            <h2><%= pluralize(turn.errors.count, "error") %> prohibited this turn from being saved:</h2>

            <ul>
              <% turn.errors.each do |error| %>
                <li><%= error.full_message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div>
          <%= form.label :date, style: "display: block" %>
          <%= form.datetime_field :date %>
        </div>

        <div>
          <%= form.label :motive, style: "display: block" %>
          <%= form.text_field :motive %>
        </div>

        <div>
          <%= form.label :sucursal_id, style: "display: block" %>
          <%= form.select :sucursal_id, options_for_select(Sucursal.all.collect { |x| [x.nombre + " (" + Locality.find(x.locality_id).name + ")", x.id] }, turn.sucursal_id), class: 'form-control' %>
        </div>
        
        <% if current_user.rol == 'personal_bancario' %>
          <div>
            <%= form.label :result, style: "display: block" %>
            <%= form.text_field :result, class: 'form-control' %>
          </div>
        <% end %>

        <div>
          <%= form.submit 'Guardar' %>
        </div>
      <% end %>
      <% if can? :create, Turn %>         
            <% Sucursal.all.each do |suc| %>
              <br>
              <p> Horarios para <%= suc.nombre %> </p>
              <table class="table-info table-striped-columns">   

                  <thead>
                      <th>Día</th>
                      <th>Apertura</th>
                      <th>Cierre</th>
                  </thead>

                  <tbody>
                      <% Horario.horarios_suc(suc.id).each do |horario|  %>
                          <tr>
                              <td> <%= horario.dia %> </td>
                              <td> <%= horario.desde.strftime("%H:%M") %> </td>
                              <td> <%= horario.hasta.strftime("%H:%M") %> </td>
                          </tr>
                      <% end %>
                  </tbody>
      
              </table>
            <% end %>
            
          </table>
        <% end %>
    </div>
  </div>
</div>

app/views/turns/_turn.html.erb
<div id="<%= dom_id turn %>">
  <p>
    <strong>Date:</strong>
    <%= turn.date %>
  </p>

  <p>
    <strong>Motive:</strong>
    <%= turn.motive %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= turn.status %>
  </p>

  <p>
    <strong>Result:</strong>
    <%= turn.result %>
  </p>

  <p>
    <strong>Sucursal:</strong>
    <%= turn.sucursal_id %>
  </p>

  <p>
    <strong>User:</strong>
    <%= turn.user_id %>
  </p>

</div>

app/views/turns/edit.html.erb
<h1>Editar turno</h1>

<%= render "form", turn: @turn %>

<br>

<div>
  <%= link_to "Ver el turno", @turn %> |
  <%= link_to "Volver al listado", turns_path %>
</div>

app/views/turns/index.html.erb
<h1> Lista de turnos </h1>
<br><br>
<% if can? :create, Turn %>
  <a href="<%= new_turn_path %>" class="btn btn-primary btn-icon-split">
    <span class="icon text-white-50">
      <i class="fas fa-flag"></i>
    </span>
    <span class="text"> Nuevo turno</span>
  </a>
<% end %>

<br><br>
<table class="table table-bordered">
  <thead>
    <th>Fecha y hora</th>
    <th>Sucursal</th>
    <th>Cliente</th>
    <th>Personal Bancario</th>
  </thead>
  <tbody>
    <% @turns.each do |turn|  %>
      <tr>
        <td> <%= turn.date.strftime("%d/%m/%y %H:%M") %> </td>
        <td> <%= turn.sucursal.nombre %> </td>
        <td> <%= turn.user.name %> </td>
        <% if !turn.employee.nil? %>
            <td><%= User.find(turn.employee.id).name %></td>
          <% else %>
            <td></td>
          <% end %>
        <td> <%= link_to "Detalles", turn_path(turn), class: "btn btn-primary" %> </td>
        <% if can? :update, Turn %>
          <% if (current_user.rol == 'personal_bancario') && (turn.status == 'pendiente')  %>
            <td> <%= link_to "Atender", edit_turn_path(turn), class: "btn btn-success" %> </td>
          <% end %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/turns/new.html.erb
<h1>Turno nuevo</h1>

<%= render "form", turn: @turn %>

<br>

<div>
  <%= link_to "Volver al listado", turns_path %>
</div>

app/views/turns/show.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1>Detalles del turno</h1>    
    
    <div class="card">
      <table class="table">
        <tr>
          <td><b>Fecha y hora: </b></td>
          <td><%= @turn.date.strftime("%d/%m/%y %H:%M") %></td>
        </tr>
        <tr>
          <td><b>Sucursal: </b></td>
          <td><%= Sucursal.find(@turn.sucursal_id).nombre %></td>
        </tr>
        <tr>
          <td><b>Motivo: </b></td>
          <td><%= @turn.motive %></td>
        </tr>
        <tr>
          <td><b>Personal Bancario: </b></td>
          <% if !@turn.employee_id.nil? %>
            <td><%= User.find(@turn.employee_id).name %></td>
          <% else %>
            <td></td>
          <% end %>
        </tr>
        <tr>
          <td><b>Resultado: </b></td>
          <td><%= @turn.result %></td>
        </tr>
        <tr>
          <td><b>Estado: </b></td>
          <td><%= @turn.status %></td>
        </tr>
      </table>
    </div>
    

    
    </div>
    <% if current_user.rol == 'cliente' && @turn.status == 'pendiente' %>
      <%= link_to "Editar turno", edit_turn_path(@turn), class: 'btn btn-warning' %>
      <%= button_to "Cancelar turno", @turn, form: { data: { turbo_confirm: "Estas seguro?" } }, method: :delete, class: 'btn btn-danger' %>
    <% end %>
    <%= link_to "Volver al listado", turns_path, class: 'btn btn-outline-primary' %>
</div>