config/routes.rb
Rails.application.routes.draw do
  resources :turns
  devise_for :users
  resources :users, path: '/users_admin'
  

  resources :localities
  resources :sucursals
    
  resources :horarios

  get 'index/home'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "index#home"
end

app/models/sucursal.rb
class Sucursal < ApplicationRecord
  belongs_to :locality
  has_many :horarios, dependent: :destroy
  has_many :turns, dependent: :destroy

  validates :nombre, uniqueness: { case_sensitive: false }
  validates :nombre, :direccion, :tel, :locality_id, presence: true 

  def self.localities_sucursal(locality)
    Sucursal.all.where(locality_id: locality)     
  end

  def self.dia_horario(turno)
    if turno.date.to_date > DateTime.now.to_date
      horarios = Horario.where(sucursal_id: turno.sucursal_id) 
      horarios.each do |hora|
        if hora.dia = turno.date.strftime("%A").downcase
          turno.date.strftime("%H:%M").between?(hora.desde.strftime("%H:%M"),hora.hasta.strftime("%H:%M"))
        end
      end
    end

  end

  def self.chequeo_eliminar(suc)
    User.where(sucursals_id: suc)
  end

end

app/controllers/sucursals_controller.rb
class SucursalsController < ApplicationController

  load_and_authorize_resource 

  before_action :set_sucursal, only: %i[ show edit update destroy ]

  # GET /sucursals or /sucursals.json
  def index
    @sucursals = Sucursal.all
  end

  # GET /sucursals/1 or /sucursals/1.json
  def show
  end

  # GET /sucursals/new
  def new
    @sucursal = Sucursal.new
  end

  # GET /sucursals/1/edit
  def edit
  end

  # POST /sucursals or /sucursals.json
  def create
    @sucursal = Sucursal.new(sucursal_params)
    @sucursal.nombre  = @sucursal.nombre.upcase #Para que se guarde en mayuscula y sepa si existe ese nombre, por como puedan escribirlos

    respond_to do |format|
      if @sucursal.save
        format.html { redirect_to sucursal_url(@sucursal), notice: "Sucursal was successfully created." }
        format.json { render :show, status: :created, location: @sucursal }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @sucursal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sucursals/1 or /sucursals/1.json
  def update
    respond_to do |format|
      if @sucursal.update(sucursal_params)
        format.html { redirect_to sucursal_url(@sucursal), notice: "Sucursal was successfully updated." }
        format.json { render :show, status: :ok, location: @sucursal }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @sucursal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sucursals/1 or /sucursals/1.json
  def destroy
    if Turn.turns_sucursal(@sucursal.id).empty?
      if Sucursal.chequeo_eliminar(@sucursal.id).empty?
        @sucursal.destroy

        respond_to do |format|
          format.html { redirect_to sucursals_url, notice: "Sucursal was successfully destroyed." }
          format.json { head :no_content }
        end
      else
        flash[:notice] = "No se puede eliminar la sucursal"
        redirect_to sucursals_url
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sucursal
      @sucursal = Sucursal.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sucursal_params
      params.require(:sucursal).permit(:nombre, :direccion, :tel, :locality_id)
    end
end

app/helpers/sucursals_helper.rb
module SucursalsHelper
end

app/views/sucursals/_form.html.erb
<div class="row">
  <div class="col-log-12">
    <div class="card p-5">
    <%= form_with(model: sucursal) do |form| %>
      <% if sucursal.errors.any? %>
        <div style="color: red">
          <h2><%= pluralize(sucursal.errors.count, "error") %> prohibited this sucursal from being saved:</h2>
    
          <ul>
            <% sucursal.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    
      <div class="form-group">
        <%= form.label :nombre, style: "display: block" %>
        <%= form.text_field :nombre, class: 'form-control' %>
      </div>
    
      <div class="form-group">
        <%= form.label :direccion, style: "display: block" %>
        <%= form.text_field :direccion, class: 'form-control' %>
      </div>
    
      <div class="form-group">
        <%= form.label :tel, style: "display: block" %>
        <%= form.text_field :tel, class: 'form-control' %>
      </div>
    
      <div class="form-group">
        <%= form.label :locality_id, style: "display: block" %>
        <%= form.select :locality_id, options_for_select(Locality.all.collect { |x| [x.name, x.id] }, Locality.name), class: 'form-control' %>
      </div>
    
      <div>
        <%= form.submit "Crear", class: 'btn btn-primary' %>
      </div>
    <% end %>
    

    </div>
  </div>
</div>

app/views/sucursals/_sucursal.html.erb
<div id="<%= dom_id sucursal %>">
  <p>
    <strong>Nombre:</strong>
    <%= sucursal.nombre %>
  </p>

  <p>
    <strong>Direccion:</strong>
    <%= sucursal.direccion %>
  </p>

  <p>
    <strong>Tel:</strong>
    <%= sucursal.tel %>
  </p>

  <p>
    <strong>Localidad:</strong>
    <%= sucursal.locality_id %>
  </p>

</div>

app/views/sucursals/edit.html.erb
<h1>Editar sucursal</h1>

<%= render "form", sucursal: @sucursal %>

<br>

<div>
  <%= link_to "Ver detalles", @sucursal %> |
  <%= link_to "Volver al listado", sucursals_path %>
</div>

app/views/sucursals/horarios.html.erb
<a href="<%= nuevo_horario_sucursal_path %>" class="btn btn-primary btn-icon-split">
    <span class="icon text-white-50">
        <i class="fas fa-flag"></i>
    </span>
    <span class="text"> Agregar horario</span>
</a>
<br><br><br>
<table class="table table-bordered">   

    <thead>
        <th>Día</th>
        <th>Apertura</th>
        <th>Cierre</th>
    </thead>

    <tbody>
        <% @horarios.each do |horario|  %>
            <tr>
                <td> <%= horario.dia %> </td>
                <td> <%= horario.desde.strftime("%H:%M") %> </td>
                <td> <%= horario.hasta.strftime("%H:%M") %> </td>
                
            </tr>
        <% end %>
    </tbody>
    
</table>
<td> <%= link_to "Volver", sucursals_path, class: "btn btn-primary" %> </td>

app/views/sucursals/index.html.erb
<center><h1> Lista de sucursales </h1></center>
<br><br>
<% if can? :create, Sucursal %>
  <a href="<%= new_sucursal_path %>" class="btn btn-primary btn-icon-split">
    <span class="icon text-white-50">
      <i class="fas fa-flag"></i>
    </span>
    <span class="text"> Crear sucursal</span>
  </a>
<% end %>
<% if can? :create, Horario %>
    <a href="<%= new_horario_path %>" class="btn btn-primary btn-icon-split">
        <span class="icon text-white-50">
            <i class="fas fa-flag"></i>
        </span>
        <span class="text"> Agregar horario</span>
    </a>
<% end %>


<br><br>
<table class="table table-bordered">
  <thead>
    <th>Nombre</th>
    <th>Direccion</th>
    <th>Telefono</th>
    <th>Localidad</th>
    <th>Horarios</th>
  </thead>
  <tbody>
    <% @sucursals.each do |sucursal|  %>
      <tr>
        <td> <%= sucursal.nombre %> </td>
        <td> <%= sucursal.direccion %> </td>
        <td> <%= sucursal.tel %> </td>
        <td> <%= Locality.find(sucursal.locality_id).name %> </td>
        <td> <%= link_to "Ver horarios", horarios_path(sucursal, id_s: sucursal.id), class: "btn btn-primary" %> </td>
        <td> <%= link_to "Detalles", sucursal_path(sucursal), class: "btn btn-primary" %> </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/sucursals/new.html.erb
<h1>Crear nueva sucursal</h1>

<%= render "form", sucursal: @sucursal %>

<br>

<div>
  <%= link_to "Volver al listado", sucursals_path %>
</div>

app/views/sucursals/show.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1>Detalles de la sucursal</h1>    
    
    <div class="card">
      <table class="table">
        <tr>
          <td><b>Nombre: </b></td>
          <td><%= @sucursal.nombre %></td>
        </tr>
        <tr>
          <td><b>Direccion: </b></td>
          <td><%= @sucursal.direccion %></td>
        </tr>
        <tr>
          <td><b>Telefono: </b></td>
          <td><%= @sucursal.tel %></td>
        </tr>
        <tr>
          <td><b>Localidad: </b></td>
          <td><%= Locality.find(@sucursal.locality_id).name %></td>
        </tr>
      </table>
    </div>
    

    
    </div>
    <% if can? :update, Sucursal %>
      <%= link_to "Editar sucursal", edit_sucursal_path(@sucursal), class: 'btn btn-warning' %>
    <% end %>
    <% if can? :delete, Sucursal %>
      <%= button_to "Eliminar sucursal", @sucursal, form: { data: { turbo_confirm: "Estas seguro?" } },method: :delete, class: 'btn btn-danger' %>
    <% end %>
    <%= link_to "Volver al listado", sucursals_path, class: 'btn btn-outline-primary' %>
</div>