config/routes.rb
Rails.application.routes.draw do
  resources :turns
  devise_for :users
  resources :users, path: '/users_admin'
  

  resources :localities
  resources :sucursals
    
  resources :horarios

  get 'index/home'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "index#home"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Banco</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>


    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Custom fonts for this template-->
    
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">


  </head>

  <body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <% if signed_in? %>        
            <!-- Sidebar -->
            <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

                <!-- Sidebar - Brand -->
                <a class="sidebar-brand d-flex align-items-center justify-content-center" href="<%= root_path %>">
                    <div class="sidebar-brand-icon rotate-n-15">
                        <i class="fas fa-laugh-wink"></i>
                    </div>
                    <div class="sidebar-brand-text mx-3">Banco Argentino</div>
                    
                </a>
                <a href='<%= user_path(current_user, profile: true) %>' class="btn btn-outline-light">Ver Perfil</a> 

                <!-- Divider -->
                <hr class="sidebar-divider my-0">

                <!-- Nav Item - Dashboard -->                
                <% if can? :read, Sucursal %>
                    <li class="nav-item">
                        <a class="nav-link" href="<%= sucursals_path %>">
                            <i class="fas fa-fw fa-tachometer-alt"></i>
                            <span>Sucursales</span></a>
                    </li>
                <% end %>

                <% if can? :read, User %>
                    <% if current_user.rol != 'cliente' %>
                        <li class="nav-item">
                            <a class="nav-link" href="<%= users_path %>">
                                <i class="fas fa-fw fa-tachometer-alt"></i>
                                <span>Usuarios</span></a>
                        </li>
                    <% end %>
                <% end %>

                <% if can? :read, Locality %>
                    <li class="nav-item">
                        <a class="nav-link" href="<%= localities_path %>">
                            <i class="fas fa-fw fa-tachometer-alt"></i>
                            <span>Localidades</span></a>
                    </li>
                <% end %>

                <% if can? :read, Turn %>
                    <li class="nav-item">
                        <a class="nav-link" href="<%= turns_path %>">
                            <i class="fas fa-fw fa-tachometer-alt"></i>
                            <span>Turnos</span></a>
                    </li>
                <% end %>

                <!-- Divider -->
                <hr class="sidebar-divider d-none d-md-block">

                <!-- Sidebar Toggler (Sidebar) -->
                <!-- <div class="text-center d-none d-md-inline">
                    <button class="rounded-circle border-0" id="sidebarToggle"></button>
                </div> --> <!--Es el boton de la flecha -->

                <!-- Cerrar Sesion -->

                <% if current_user %>
                    <%= link_to 'Cerrar Sesión', destroy_user_session_path, method: :delete, class: 'btn btn-outline-light' %>
                <% else %>
                    <%= link_to 'Iniciar Sesión', new_user_session_path %>
                <% end %>

            </ul>
            <!-- End of Sidebar -->
        <% end %>
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <!-- <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow"> -->
                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>
                </nav>

                <!-- End of Topbar -->

                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!-- Page Heading -->
                    <%= yield %>

                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Your Website 2020</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="login.html">Logout</a>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript--> <!-- Tiran error --> <!-- Ya modifique las rutas y nada -->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script> 
    
    <!-- Core plugin JavaScript-->
    <script src="vendor/jquery-easing/jquery.easing.min.js"></script>
    
    <!-- Custom scripts for all pages-->
    <script src="js/sb-admin-2.min.js"></script>

</body>

</html>